name: Gatekeeper

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gatekeeper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn

      # Check if developers forgot to prettify the code
      - name: Prettier check
        run: yarn prettier

      # Lint the code with ESLint and TSC for any code issues
      - name: ESLint & TSC check
        run: yarn eslint:no-glob . && yarn tslint

      # In case everything is fine, build the package
      - name: Bundle package
        run: yarn build

      # Verify if the package exports are correct
      - name: Verify exports
        run: yarn verify:exports
