name: Gatekeeper

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gatekeeper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn

      - name: Verify coding style
        run: yarn prettier

      - name: Lint code
        run: yarn eslint:no-glob . && yarn tslint

      - name: Bundle package
        run: yarn build

      - name: Verify exports
        run: yarn verify:exports
